import Link from "next/link";

export function Footer() {
  const year = new Date().getFullYear();
  return (
    <footer className="hairline mt-32">
      <div className="container-edge py-16 grid gap-14 md:grid-cols-12">
        <div className="md:col-span-6">
          <p className="font-display text-[clamp(1.75rem,3.5vw,2.75rem)] leading-[1.05] tracking-tightest max-w-[22ch]">
            Have a campaign in mind? Let&apos;s build it.
          </p>
          <Link
            href="/contact"
            className="inline-flex items-center gap-2 mt-8 text-sm uppercase tracking-wider2 text-ink hover:text-accent transition-colors"
          >
            <span>Start a brief</span>
            <span aria-hidden>→</span>
          </Link>
        </div>

        <div className="md:col-span-3 md:col-start-8">
          <p className="eyebrow mb-4">Contact</p>
          <ul className="space-y-2 text-sm">
            <li>
              <a
                href="mailto:fabian.arndt.info@gmail.com"
                className="hover:text-accent transition-colors"
              >
                fabian.arndt.info@gmail.com
              </a>
            </li>
            <li>
              <a
                href="https://instagram.com/"
                className="hover:text-accent transition-colors"
                target="_blank"
                rel="noreferrer"
              >
                Instagram ↗
              </a>
            </li>
          </ul>
        </div>

        <div className="md:col-span-2">
          <p className="eyebrow mb-4">Studio</p>
          <ul className="space-y-2 text-sm">
            <li>
              <Link href="/" className="hover:text-accent transition-colors">
                Work
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover:text-accent transition-colors">
                About
              </Link>
            </li>
            <li>
              <Link href="/contact" className="hover:text-accent transition-colors">
                Book
              </Link>
            </li>
          </ul>
        </div>
      </div>

      <div className="container-edge pb-10 flex items-center justify-between text-xs text-ink-mute">
        <span className="font-display lowercase tracking-tightest text-[0.9rem] text-ink-soft">
          by<span className="italic">fabian</span>
        </span>
        <span className="serial">© {year} — all imagery AI-generated by ByFabian</span>
      </div>
    </footer>
  );
}
