// AUTO-GENERATED by scripts/sync-campaigns.ts — do not edit by hand.
// Campaign metadata lives in public/images/<model>/<campaign>/campaign.json.
// Model metadata lives in public/images/<model>/model.json.

import type { Aspect, Campaign, Model } from "./types";

export const models: Model[] = [
{
  "slug": "yamada",
  "name": "Yamada",
  "bio": "A quiet-eyed muse in motion. Yamada anchors ByFabian's first body of work — a single character reshaped across beauty, streetwear, and activewear."
}
];

export const campaigns: Campaign[] = [
{
  "slug": "yamada-face-expressions",
  "title": "Face",
  "number": "01",
  "modelSlug": "yamada",
  "modelName": "Yamada",
  "category": "Beauty Editorial",
  "year": 2026,
  "tagline": "Ten frames. One unguarded hour.",
  "description": "A study in close quiet. No wardrobe, no set — just natural window light, bare skin, and the small shifts of a face that has nothing to prove. The series reads like a casting tape for someone who already has the part.",
  "tools": [
    "Flux 1.1",
    "ComfyUI",
    "Lightroom"
  ],
  "cover": "/images/yamada/face-expressions/01.jpg",
  "coverAspect": "portrait",
  "heroFrame": "03",
  "heroImage": {
    "id": "03",
    "src": "/images/yamada/face-expressions/03.jpg",
    "alt": "Yamada — Face — frame 03",
    "width": 1792,
    "height": 2400,
    "aspect": "portrait",
    "feature": true
  },
  "draft": false,
  "images": [
    {
      "id": "01",
      "src": "/images/yamada/face-expressions/01.jpg",
      "alt": "Yamada — Face — frame 01",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "02",
      "src": "/images/yamada/face-expressions/02.jpg",
      "alt": "Yamada — Face — frame 02",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "03",
      "src": "/images/yamada/face-expressions/03.jpg",
      "alt": "Yamada — Face — frame 03",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": true
    },
    {
      "id": "04",
      "src": "/images/yamada/face-expressions/04.jpg",
      "alt": "Yamada — Face — frame 04",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "05",
      "src": "/images/yamada/face-expressions/05.jpg",
      "alt": "Yamada — Face — frame 05",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "06",
      "src": "/images/yamada/face-expressions/06.jpg",
      "alt": "Yamada — Face — frame 06",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": true
    },
    {
      "id": "07",
      "src": "/images/yamada/face-expressions/07.jpg",
      "alt": "Yamada — Face — frame 07",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "08",
      "src": "/images/yamada/face-expressions/08.jpg",
      "alt": "Yamada — Face — frame 08",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "09",
      "src": "/images/yamada/face-expressions/09.jpg",
      "alt": "Yamada — Face — frame 09",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "10",
      "src": "/images/yamada/face-expressions/10.jpg",
      "alt": "Yamada — Face — frame 10",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    }
  ]
},
{
  "slug": "yamada-bomber-jacket",
  "title": "Bomber",
  "number": "02",
  "modelSlug": "yamada",
  "modelName": "Yamada",
  "category": "Streetwear Editorial",
  "year": 2026,
  "tagline": "Cold wall, warm stare.",
  "description": "Platinum hair against a bleached-out wall. A bomber that's seen things. This was the mood-board test that became a campaign — proof that a single model can carry editorial weight without a crew, a location scout, or a plane ticket.",
  "tools": [
    "Flux 1.1",
    "ComfyUI",
    "Magnific"
  ],
  "cover": "/images/yamada/bomber-jacket/01.jpg",
  "coverAspect": "landscape",
  "heroFrame": "01",
  "heroImage": {
    "id": "01",
    "src": "/images/yamada/bomber-jacket/01.jpg",
    "alt": "Yamada — Bomber — frame 01",
    "width": 2400,
    "height": 1792,
    "aspect": "landscape",
    "feature": true
  },
  "draft": false,
  "images": [
    {
      "id": "01",
      "src": "/images/yamada/bomber-jacket/01.jpg",
      "alt": "Yamada — Bomber — frame 01",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": true
    },
    {
      "id": "02",
      "src": "/images/yamada/bomber-jacket/02.jpg",
      "alt": "Yamada — Bomber — frame 02",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "03",
      "src": "/images/yamada/bomber-jacket/03.jpg",
      "alt": "Yamada — Bomber — frame 03",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "04",
      "src": "/images/yamada/bomber-jacket/04.jpg",
      "alt": "Yamada — Bomber — frame 04",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "05",
      "src": "/images/yamada/bomber-jacket/05.jpg",
      "alt": "Yamada — Bomber — frame 05",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": true
    },
    {
      "id": "06",
      "src": "/images/yamada/bomber-jacket/06.jpg",
      "alt": "Yamada — Bomber — frame 06",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "07",
      "src": "/images/yamada/bomber-jacket/07.jpg",
      "alt": "Yamada — Bomber — frame 07",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "08",
      "src": "/images/yamada/bomber-jacket/08.jpg",
      "alt": "Yamada — Bomber — frame 08",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    }
  ]
},
{
  "slug": "yamada-alo",
  "title": "ALO",
  "number": "03",
  "modelSlug": "yamada",
  "modelName": "Yamada",
  "category": "Activewear Campaign",
  "year": 2026,
  "tagline": "Los Angeles, twenty minutes before blue hour.",
  "description": "An activewear campaign concept shot on a rooftop that doesn't exist, with a model that doesn't exist, at a golden hour that was every golden hour. Built to show how ByFabian can deliver a full brand campaign — on-location energy without the location budget.",
  "tools": [
    "Flux 1.1",
    "ComfyUI",
    "Topaz"
  ],
  "cover": "/images/yamada/alo/01.jpg",
  "coverAspect": "landscape",
  "heroFrame": "01",
  "heroImage": {
    "id": "01",
    "src": "/images/yamada/alo/01.jpg",
    "alt": "Yamada — ALO — frame 01",
    "width": 2400,
    "height": 1792,
    "aspect": "landscape",
    "feature": true
  },
  "draft": false,
  "images": [
    {
      "id": "01",
      "src": "/images/yamada/alo/01.jpg",
      "alt": "Yamada — ALO — frame 01",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": true
    },
    {
      "id": "02",
      "src": "/images/yamada/alo/02.jpg",
      "alt": "Yamada — ALO — frame 02",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "03",
      "src": "/images/yamada/alo/03.jpg",
      "alt": "Yamada — ALO — frame 03",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "04",
      "src": "/images/yamada/alo/04.jpg",
      "alt": "Yamada — ALO — frame 04",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "05",
      "src": "/images/yamada/alo/05.jpg",
      "alt": "Yamada — ALO — frame 05",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "06",
      "src": "/images/yamada/alo/06.jpg",
      "alt": "Yamada — ALO — frame 06",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "07",
      "src": "/images/yamada/alo/07.jpg",
      "alt": "Yamada — ALO — frame 07",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": true
    },
    {
      "id": "08",
      "src": "/images/yamada/alo/08.jpg",
      "alt": "Yamada — ALO — frame 08",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "09",
      "src": "/images/yamada/alo/09.jpg",
      "alt": "Yamada — ALO — frame 09",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "10",
      "src": "/images/yamada/alo/10.jpg",
      "alt": "Yamada — ALO — frame 10",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    }
  ]
},
{
  "slug": "yamada-mix",
  "title": "Mix",
  "number": "04",
  "modelSlug": "yamada",
  "modelName": "Yamada",
  "category": "Editorial",
  "year": 2026,
  "tagline": "A new campaign. Fresh frames.",
  "description": "A campaign description — swap this text with the brief, the feel, the reason the work exists.",
  "tools": [
    "Flux 1.1",
    "ComfyUI"
  ],
  "cover": "/images/yamada/mix/01.jpg",
  "coverAspect": "landscape",
  "heroImage": {
    "id": "01",
    "src": "/images/yamada/mix/01.jpg",
    "alt": "Yamada — Mix — frame 01",
    "width": 2400,
    "height": 1792,
    "aspect": "landscape",
    "feature": false
  },
  "draft": true,
  "images": [
    {
      "id": "01",
      "src": "/images/yamada/mix/01.jpg",
      "alt": "Yamada — Mix — frame 01",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "02",
      "src": "/images/yamada/mix/02.jpg",
      "alt": "Yamada — Mix — frame 02",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "03",
      "src": "/images/yamada/mix/03.jpg",
      "alt": "Yamada — Mix — frame 03",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "04",
      "src": "/images/yamada/mix/04.jpg",
      "alt": "Yamada — Mix — frame 04",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    },
    {
      "id": "05",
      "src": "/images/yamada/mix/05.jpg",
      "alt": "Yamada — Mix — frame 05",
      "width": 2400,
      "height": 1792,
      "aspect": "landscape",
      "feature": false
    },
    {
      "id": "06",
      "src": "/images/yamada/mix/06.jpg",
      "alt": "Yamada — Mix — frame 06",
      "width": 1792,
      "height": 2400,
      "aspect": "portrait",
      "feature": false
    }
  ]
}
];

export type { Aspect, Campaign, Model };
